export const websites = [
  {
    id: 1,
    name: "Latte Larry's",
    url: "https://latte-larrys.netlify.app",
    pic: "website-pics/latte-larrys.png",
    desc: "A storefront website for coffee, made with HTML and CSS",
    tags: "HTML, CSS, Bulma, JS",
  },
  {
    id: 2,
    name: "Restaurant Menu",
    url: "https://restaurant-menu-demo.netlify.app",
    pic: "website-pics/menu.png",
    desc: "A restaurant website with filtering, made with React",
    tags: "HTML, CSS, JS, React",
  },
  {
    id: 3,
    name: "Reviews",
    url: "https://reviews-site.netlify.app",
    pic: "website-pics/reviews.png",
    desc: "A website with testimonials, made with React",
    tags: "HTML, CSS, JS, React",
  },
  {
    id: 4,
    name: "Tours",
    url: "https://tours-demosite.netlify.app",
    pic: "website-pics/tours.png",
    desc: "A website with different tour packages, made with React",
    tags: "HTML, CSS, JS, React",
  },
  {
    id: 5,
    name: "Accordion",
    url: "https://accordion-collapsible.netlify.app",
    pic: "website-pics/accordion.png",
    desc: "A website to practice collapsible boxes, made with React",
    tags: "HTML, CSS, JS, React",
  },
  {
    id: 6,
    name: "Markdown Previewer",
    url: "https://codepen.io/RamanH/pen/xxZapaj",
    pic: "website-pics/markdown.png",
    desc: "Website that translates markdown language into HTML",
    tags: "HTML, CSS, JS, Bootstrap, React",
  },
  {
    id: 7,
    name: "Survey Form",
    url: "https://codepen.io/RamanH/pen/LYGpjYd",
    pic: "website-pics/survey.png",
    desc: "A website that takes inputs",
    tags: "HTML, CSS",
  },
  {
    id: 8,
    name: "Technical Documentation",
    url: "https://codepen.io/RamanH/pen/zYrqVNX",
    pic: "website-pics/documentation.png",
    desc: "Website that contains documentation with sidebar for navigation",
    tags: "HTML, CSS",
  },
  {
    id: 9,
    name: "Quote Machine",
    url: "https://codepen.io/RamanH/pen/LYGroXZ",
    pic: "website-pics/quotes.png",
    desc:
      "Website that displays random Naruto Quotes with random backgrounds, made with React",
    tags: "HTML, CSS, JS, React",
  },
  {
    id: 10,
    name: "Drum Kit",
    url: "https://codepen.io/RamanH/pen/ExPGLbV",
    pic: "website-pics/drums.png",
    desc:
      "Website that can play certain drums with mouse or key clicks, made with React",
    tags: "HTML, CSS, JS, React",
  },
];
