export const websites = [
  {
    id: 1,
    name: "Latte Larry's",
    url: "https://latte-larrys.netlify.app",
    pic: "website-pics/latte-larrys.png",
    desc: "desc",
  },
  {
    id: 2,
    name: "Restaurant Menu",
    url: "https://restaurant-menu-demo.netlify.app",
    pic: "website-pics/menu.png",
    desc: "",
  },
  {
    id: 3,
    name: "Reviews",
    url: "https://reviews-site.netlify.app",
    pic: "website-pics/reviews.png",
    desc: "",
  },
  {
    id: 4,
    name: "Tours",
    url: "https://tours-demosite.netlify.app",
    pic: "website-pics/tours.png",
    desc: "",
  },
  {
    id: 5,
    name: "Accordion",
    url: "https://accordion-collapsible.netlify.app",
    pic: "website-pics/accordion.png",
    desc: "",
  },
  {
    id: 6,
    name: "Markdown Previewer",
    url: "https://codepen.io/RamanH/pen/xxZapaj",
    pic: "website-pics/markdown.png",
    desc: "",
  },
  {
    id: 7,
    name: "Survey Form",
    url: "https://codepen.io/RamanH/pen/LYGpjYd",
    pic: "website-pics/survey.png",
    desc: "",
  },
  {
    id: 8,
    name: "Technical Documentation",
    url: "https://codepen.io/RamanH/pen/zYrqVNX",
    pic: "website-pics/documentation.png",
    desc: "",
  },
  {
    id: 9,
    name: "Quote Machine",
    url: "https://codepen.io/RamanH/pen/LYGroXZ",
    pic: "website-pics/quotes.png",
    desc: "",
  },
  {
    id: 10,
    name: "Drum Kit",
    url: "https://codepen.io/RamanH/pen/ExPGLbV",
    pic: "website-pics/drums.png",
    desc: "",
  },
];
